### ISSUE TITLE
Awesome Thinsboard collection

### ISSUE THREAD

**Issue by devaskim** [abferguson/Park-Assist-with-Thingsboard-and-Telegram#1]
Hi
I want to create a collection of [awesome Thingsboard things](https://github.com/devaskim/awesome-thingsboard) to help community (and me too :) ) to speed up the develompent of their projects. If you don't mind I will add link to this project. Is it OK for you?

Also I have a questions. At the source code of this project I see absent source links, e.g. Thingsboard.h, are you going to add them or it is commercial secret?

Thanks in advance

**Comment by abferguson** [comment]
Sure. Thingsboard.h is from the Thingsboard SDK library on Github or the Arduino IDE. All libraries in this project are available through the Arduino IDE.

**Comment by devaskim** [comment]
Thanks
